import { Piece } from "../../classes/Piece.jsx";

const P1 = new Piece(
  "1",
  "Twinkle, Twinkle, Little Star",
  "Playing Twinkle, Twinkle, Little Star on the piano is the ultimate beginner's rite of passage. Its memorable A-B-C-C-A-B song structure uses only six white keys in the C major scale—Middle C through A. The melody is highly repetitive, making it incredibly easy to memorize and play by ear!",
  "twinkletwinklelittlestar",
  "/Pieces/P1.jpg",
  "Jane Taylor",
  "1",
  "/AssetsForPiano/cartoonCloud.png",
  "/AssetsForPiano/cartoonMoon.png",
  "/AssetsForPiano/none.png",
  "/AssetsForPiano/cartoonCloud.png",
  "/AssetsForPiano/cartoonStars.png",
  "/AssetsForPiano/cartoonStars.png",
  [
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "G5", fingers: "4", duration: 0.5 },
    { chord: "G5", fingers: "4", duration: 0.5 },
    { chord: "A5", fingers: "5", duration: 0.5 },
    { chord: "A5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "4", duration: 1.0 },

    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 1.0 },

    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 1.0 },

    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 1.0 },

    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "G5", fingers: "4", duration: 0.5 },
    { chord: "G5", fingers: "4", duration: 0.5 },
    { chord: "A5", fingers: "5", duration: 0.5 },
    { chord: "A5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "4", duration: 1.0 },

    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 1.0 },
  ],
  [
    { chord: "C4", fingers: "5", duration: 1.0 },
    { chord: "E4", fingers: "3", duration: 1.0 },
    { chord: "F4", fingers: "2", duration: 1.0 },
    { chord: "E4", fingers: "3", duration: 1.0 },

    { chord: "D4", fingers: "4", duration: 1.0 },
    { chord: "C4", fingers: "5", duration: 1.0 },
    { chord: "F4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "C4", fingers: "5", duration: 1.0 },

    { chord: "E4", fingers: "3", duration: 1.0 },
    { chord: "D4", fingers: "4", duration: 1.0 },
    { chord: "C4", fingers: "5", duration: 1.0 },
    { chord: "G4", fingers: "1", duration: 1.0 },

    { chord: "E4", fingers: "3", duration: 1.0 },
    { chord: "D4", fingers: "4", duration: 1.0 },
    { chord: "C4", fingers: "5", duration: 1.0 },
    { chord: "G4", fingers: "1", duration: 1.0 },

    { chord: "C4", fingers: "5", duration: 1.0 },
    { chord: "E4", fingers: "3", duration: 1.0 },
    { chord: "F4", fingers: "2", duration: 1.0 },
    { chord: "E4", fingers: "3", duration: 1.0 },

    { chord: "D4", fingers: "4", duration: 1.0 },
    { chord: "C4", fingers: "5", duration: 1.0 },
    { chord: "F4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "C4", fingers: "5", duration: 1.0 },
  ]
);

export default P1;