import { Piece } from "../../classes/Piece.jsx";

const P10 = new Piece(
  "10",
  "Fur Elise",
  `Für Elise is one of the most popular piano pieces ever written. Elise's identity has eluded historians for decades — much like Beethoven's other mystery woman, the "Immortal Beloved" of his letters. The piece wasn't published until 40 years after his death, so he was never around to explain who inspired it. Scholars believe Elise was likely close to him, but no one has definitively proven who she really was.`,
  "furelise",
  "/Pieces/P10.png",
  "#F5D576",
  "Ludwig van Beethoven",
  "4",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/shiningMoon.png",
  "/AssetsForPiano/cherryBlossom.png",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/flyingBird.png",
  "/AssetsForPiano/cloud.png",
  [
    { chord: "", duration: 1.0 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.75 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "G#4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.75 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "A4", fingers: "3", duration: 0.75 },

    { chord: "B4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "3", duration: 0.25 },
    { chord: "E5", fingers: "4", duration: 0.75 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "F5", fingers: "5", duration: 0.25 },
    { chord: "E5", fingers: "4", duration: 0.25 },
    { chord: "D5", fingers: "3", duration: 0.75 },
    { chord: "F4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "D5", fingers: "5", duration: 0.25 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.75 },

    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.75 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "G#4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.75 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "A4", fingers: "3", duration: 0.75 },

    { chord: "E4 C5", fingers: "1 5", duration: 0.25 },
    { chord: "F4 C5", fingers: "2 5", duration: 0.25 },
    { chord: "G4 C5", fingers: "3 5", duration: 0.25 },
    { chord: "F4 A4 C5", fingers: "1 3 5", duration: 1.0 },
    { chord: "F5", fingers: "4", duration: 0.375 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "E5", fingers: "2", duration: 0.5 },
    { chord: "D5", fingers: "1", duration: 0.5 },
    { chord: "A#5", fingers: "4", duration: 0.375 },
    { chord: "A5", fingers: "3", duration: 0.125 },
    { chord: "A5", fingers: "2", duration: 0.25 },
    { chord: "G5", fingers: "1", duration: 0.25 },
    { chord: "F5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D5", fingers: "2", duration: 0.25 },
    { chord: "C5", fingers: "1", duration: 0.25 },
    { chord: "A#4", fingers: "4", duration: 0.5 },
    { chord: "A4", fingers: "3", duration: 0.375 },
    { chord: "A#4", fingers: "4", duration: 0.125 },
    { chord: "A4", fingers: "3", duration: 0.125 },
    { chord: "G4", fingers: "2", duration: 0.125 },
    { chord: "A4", fingers: "3", duration: 0.125 },
    { chord: "A#4", fingers: "4", duration: 0.125 },

    { chord: "C5", fingers: "5", duration: 1.0 },
    { chord: "D5", fingers: "1", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.75 },
    { chord: "E5", fingers: "4", duration: 0.25 },
    { chord: "F5", fingers: "5", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "2", duration: 0.5 },
    { chord: "D5", fingers: "3", duration: 0.125 },
    { chord: "C5", fingers: "2", duration: 0.125 },
    { chord: "B4", fingers: "1", duration: 0.125 },
    { chord: "C5", fingers: "2", duration: 0.125 },
    { chord: "D5", fingers: "3", duration: 0.375 },
    { chord: "B4", fingers: "1", duration: 0.125 },

    { chord: "C5", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "G4", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "A4", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "B4", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "C5", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "D5", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "E5", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "2", duration: 0.125 },
    { chord: "C6", fingers: "5", duration: 0.125 },
    { chord: "B5", fingers: "4", duration: 0.125 },
    { chord: "A5", fingers: "3", duration: 0.125 },
    { chord: "G5", fingers: "2", duration: 0.125 },
    { chord: "F5", fingers: "1", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "D5", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "F5", fingers: "4", duration: 0.125 },
    { chord: "D5", fingers: "2", duration: 0.125 },
    { chord: "C5", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "G4", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "A4", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "B4", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "C5", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "D5", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "E5", fingers: "1", duration: 0.125 },
    { chord: "G5", fingers: "2", duration: 0.125 },
    { chord: "C6", fingers: "5", duration: 0.125 },
    { chord: "B5", fingers: "4", duration: 0.125 },
    { chord: "A5", fingers: "3", duration: 0.125 },
    { chord: "G5", fingers: "2", duration: 0.125 },
    { chord: "F5", fingers: "1", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "D5", fingers: "2", duration: 0.125 },
    { chord: "G5", fingers: "5", duration: 0.125 },
    { chord: "F5", fingers: "4", duration: 0.125 },
    { chord: "D5", fingers: "2", duration: 0.125 },

    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "F5", fingers: "4", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "D#5", fingers: "2", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "B4", fingers: "1", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "D#5", fingers: "2", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "B4", fingers: "1", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.125 },
    { chord: "D#5", fingers: "2", duration: 0.125 },
    { chord: "E5", fingers: "3", duration: 0.75 },
    { chord: "B4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.75 },
    { chord: "B4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "D#5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "B4", fingers: "1", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.75 },

    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "G#4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.75 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "D#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "4", duration: 0.25 },
    { chord: "C5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.75 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "5", duration: 0.75 },
    { chord: "D4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.25 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "C4 A4", fingers: "1 3", duration: 3.0 },
  ],
  [
    { chord: "", duration: 3.0 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },

    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 0.75 },

    { chord: "A#3 C4", fingers: "2 1", duration: 0.25 },
    { chord: "A3 C4", fingers: "3 1", duration: 0.25 },
    { chord: "G3 C4", fingers: "4 1", duration: 0.25 },
    { chord: "F3", fingers: "5", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "F3", fingers: "5", duration: 0.25 },
    { chord: "A#3", fingers: "2", duration: 0.25 },
    { chord: "D4", fingers: "1", duration: 0.25 },
    { chord: "A#3", fingers: "2", duration: 0.25 },
    { chord: "D4", fingers: "1", duration: 0.25 },
    { chord: "A#3", fingers: "2", duration: 0.25 },
    { chord: "F3", fingers: "5", duration: 0.25 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "F3 G3 A#3", fingers: "5 4 2", duration: 0.25 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "F3 G3 A#3", fingers: "5 4 2", duration: 0.25 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "F3", fingers: "5", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },

    { chord: "F3", fingers: "5", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },
    { chord: "E3", fingers: "5", duration: 0.25 },
    { chord: "A3", fingers: "2", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "A3", fingers: "2", duration: 0.25 },
    { chord: "D3 D4", fingers: "5 1", duration: 0.25 },
    { chord: "F3", fingers: "4", duration: 0.25 },
    { chord: "G3", fingers: "3", duration: 0.25 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "G3", fingers: "5", duration: 0.25 },
    { chord: "E4", fingers: "1", duration: 0.25 },
    { chord: "G3", fingers: "5", duration: 0.25 },
    { chord: "F4", fingers: "1", duration: 0.25 },

    { chord: "C4", fingers: "4", duration: 0.5 },
    { chord: "", duration: 0.25 },
    { chord: "F4 G4", fingers: "2 1", duration: 0.25 },
    { chord: "E4 G4", fingers: "3 1", duration: 0.25 },
    { chord: "D4 F4 G4", fingers: "4 2 1", duration: 0.25 },
    { chord: "C4 E4 G4", fingers: "5 3 1", duration: 0.5 },
    { chord: "F3 A3", fingers: "5 3", duration: 0.5 },
    { chord: "G3 B3", fingers: "4 2", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "", duration: 0.25 },
    { chord: "F4 G4", fingers: "2 1", duration: 0.25 },
    { chord: "E4 G4", fingers: "3 1", duration: 0.25 },
    { chord: "D4 F4 G4", fingers: "4 2 1", duration: 0.25 },
    { chord: "C4 E4 G4", fingers: "5 3 1", duration: 0.5 },
    { chord: "F3 A3", fingers: "5 3", duration: 0.5 },
    { chord: "G3 B3", fingers: "4 2", duration: 0.5 },
    { chord: "G#3 B3", fingers: "3 1", duration: 0.5 },
    { chord: "", duration: 7.0 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 3.0 },
  ]
);

export default P10;