import { Piece } from "../../classes/Piece.jsx";

const P12 = new Piece(
  "12",
  "Bach's Minuet",
  `The Minuets in G major and G minor, BWV Anh. 114 and 115, are a pair of movements from a suite for harpsichord by Christian Petzold in 1720, which, through their appearance in the 1725 Notebook for Anna Magdalena Bach, used to be attributed to Johann Sebastian Bach. These minuets, which are suitable for beginners on the piano, are among the best known pieces of music literature. The 1965 pop song "A Lover's Concerto", of which millions of copies were sold, is based on the first of these Minuets.`,
  "bachminuet",
  "/Pieces/P12.png",
  "Christian Petzold",
  "5",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/shiningMoon.png",
  "/AssetsForPiano/cherryBlossom.png",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/flyingBird.png",
  "/AssetsForPiano/cloud.png",
  [
    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "E5", fingers: "5", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.25 },
    { chord: "D5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "F#5", fingers: "4", duration: 0.25 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.5 },
    { chord: "D5", fingers: "5", duration: 0.25 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "F#4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 1.5 },

    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "E5", fingers: "5", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.25 },
    { chord: "D5", fingers: "2", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "F#5", fingers: "4", duration: 0.25 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.5 },
    { chord: "D5", fingers: "5", duration: 0.25 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.5 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "F#4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 1.5 },

    { chord: "B5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "3", duration: 0.25 },
    { chord: "A5", fingers: "4", duration: 0.25 },
    { chord: "B5", fingers: "5", duration: 0.25 },
    { chord: "G5", fingers: "3", duration: 0.25 },
    { chord: "A5", fingers: "4", duration: 0.5 },
    { chord: "D5", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "2", duration: 0.25 },
    { chord: "F#5", fingers: "3", duration: 0.25 },
    { chord: "D5", fingers: "1", duration: 0.25 },
    { chord: "G5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "2", duration: 0.25 },
    { chord: "F#5", fingers: "3", duration: 0.25 },
    { chord: "G5", fingers: "4", duration: 0.25 },
    { chord: "D5", fingers: "1", duration: 0.25 },
    { chord: "C#5", fingers: "3", duration: 0.5 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "C#5", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "A4", fingers: "1", duration: 0.25 },
    { chord: "B4", fingers: "2", duration: 0.25 },
    { chord: "C#5", fingers: "3", duration: 0.25 },
    { chord: "D5", fingers: "1", duration: 0.25 },
    { chord: "E5", fingers: "2", duration: 0.25 },
    { chord: "F#5", fingers: "3", duration: 0.25 },
    { chord: "G5", fingers: "4", duration: 0.5 },
    { chord: "F#5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "2", duration: 0.5 },
    { chord: "F#5", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "C#5", fingers: "2", duration: 0.5 },
    { chord: "D5", fingers: "3", duration: 1.5 },
    
    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "F#4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "E5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "F#4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.5 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "F#4", fingers: "2", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.25 },
    { chord: "E4", fingers: "2", duration: 0.25 },
    { chord: "F#4", fingers: "3", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.25 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "C5", fingers: "4", duration: 0.5 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "2", duration: 0.5 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "D5", fingers: "5", duration: 0.25 },
    { chord: "G4", fingers: "1", duration: 0.5 },
    { chord: "F#4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 1.5 },
  ],
  [
    { chord: "G3", fingers: "5", duration: 1.0 },
    { chord: "A3", fingers: "4", duration: 0.5 },
    { chord: "B3", fingers: "3", duration: 1.5 },
    { chord: "C4", fingers: "2", duration: 1.5 },
    { chord: "B3", fingers: "3", duration: 1.5 },
    { chord: "A3", fingers: "4", duration: 1.5 },
    { chord: "G3", fingers: "5", duration: 1.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "G3", fingers: "5", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "D3", fingers: "5", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "B3", fingers: "2", duration: 0.25 },
    { chord: "A3", fingers: "3", duration: 0.25 },

    { chord: "B3", fingers: "3", duration: 1.0 },
    { chord: "A3", fingers: "4", duration: 0.5 },
    { chord: "G3", fingers: "5", duration: 0.5 },
    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "G3", fingers: "5", duration: 0.5 },
    { chord: "C4", fingers: "2", duration: 1.5 },
    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "C4", fingers: "2", duration: 0.25 },
    { chord: "B3", fingers: "3", duration: 0.25 },
    { chord: "A3", fingers: "4", duration: 0.25 },
    { chord: "G3", fingers: "5", duration: 0.25 },
    { chord: "A3", fingers: "1", duration: 1.0 },
    { chord: "F#3", fingers: "3", duration: 0.5 },
    { chord: "G3", fingers: "2", duration: 1.0 },
    { chord: "B3", fingers: "1", duration: 0.5 },
    { chord: "C4", fingers: "2", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "D3", fingers: "5", duration: 0.5 },
    { chord: "G3", fingers: "2", duration: 1.5 },

    { chord: "G3", fingers: "2", duration: 1.5 },
    { chord: "F#3", fingers: "3", duration: 1.5 },
    { chord: "E3", fingers: "4", duration: 0.5 },
    { chord: "G3", fingers: "2", duration: 0.5 },
    { chord: "E3", fingers: "4", duration: 0.5 },
    { chord: "A3", fingers: "1", duration: 1.5 },
    { chord: "A3", fingers: "4", duration: 1.5 },
    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "C#4", fingers: "2", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "F#3", fingers: "4", duration: 0.5 },
    { chord: "A3", fingers: "2", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "D3", fingers: "5", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },

    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 0.5 },
    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "C4", fingers: "2", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 0.5 },
    { chord: "C4", fingers: "2", duration: 0.5 },
    { chord: "B3", fingers: "3", duration: 0.5 },
    { chord: "A3", fingers: "4", duration: 0.5 },
    { chord: "G3", fingers: "5", duration: 0.5 },
    { chord: "D4", fingers: "1", duration: 1.5 },
    { chord: "D3", fingers: "5", duration: 1.0 },
    { chord: "F#3", fingers: "3", duration: 0.5 },
    { chord: "E3", fingers: "4", duration: 0.5 },
    { chord: "G3", fingers: "2", duration: 0.5 },
    { chord: "F#3", fingers: "3", duration: 0.5 },
    { chord: "G3", fingers: "2", duration: 1.0 },
    { chord: "D3", fingers: "5", duration: 0.5 },
    { chord: "G3", fingers: "2", duration: 1.5 },
  ]
);

export default P12;