import { Piece } from "../../classes/Piece.jsx";

const P2 = new Piece(
  "2",
  "The Entertainer",
  "The Entertainer is one of the most iconic and instantly recognizable piano pieces ever written. Composed by Scott Joplin, this lively ragtime classic has a bouncy, upbeat feel that makes it impossible not to smile while playing. Once you learn it, you'll find yourself coming back to it again and again!",
  "theentertainer",
  "/Pieces/P2.jpg",
  "Scott Joplin",
  "2",
  "/AssetsForPiano/balloons.png",
  "/AssetsForPiano/firework.png",
  "/AssetsForPiano/magicHat.png",
  "/AssetsForPiano/balloons.png",
  "/AssetsForPiano/carnival.png",
  "/AssetsForPiano/firework.png",
  [
    { chord: "", duration: 1.0 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 1.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "D#5", fingers: "3", duration: 0.2 },
    { chord: "E5", fingers: "4", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "B4", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "3", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 1.2 },
    { chord: "", duration: 0.6 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 1.4 },
    { chord: "", duration: 0.8 },
    { chord: "C5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "D5", fingers: "3", duration: 0.2 },
    { chord: "C5", fingers: "2", duration: 0.2 },
    { chord: "A4", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "3", duration: 1.2 },
    { chord: "", duration: 0.6 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 1.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "D#5", fingers: "3", duration: 0.2 },
    { chord: "E5", fingers: "4", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "B4", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "3", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 1.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "B4", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "3", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 1.2 },
    { chord: "", duration: 0.4 },
  ],
  [
    { chord: "", duration: 0.4 },
    { chord: "D4", fingers: "3", duration: 0.2 },
    { chord: "D#4", fingers: "2", duration: 0.2 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 4.6 },
    { chord: "D4", fingers: "3", duration: 0.2 },
    { chord: "D#4", fingers: "2", duration: 0.2 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 1.4 },
    { chord: "A4", fingers: "1", duration: 0.2 },
    { chord: "G4", fingers: "2", duration: 0.2 },
    { chord: "F#4", fingers: "3", duration: 0.2 },
    { chord: "A4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 2.4 },
    { chord: "D4", fingers: "3", duration: 0.2 },
    { chord: "D#4", fingers: "2", duration: 0.2 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.2 },
    { chord: "", duration: 5.0 },
    { chord: "C4", fingers: "1", duration: 0.8 },
    { chord: "A#3", fingers: "2", duration: 0.8 },
    { chord: "A3", fingers: "3", duration: 0.8 },
    { chord: "G#3", fingers: "4", duration: 0.8 },
    { chord: "G3", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "1", duration: 0.4 },
    { chord: "G3", fingers: "2", duration: 0.4 },
    { chord: "C3", fingers: "5", duration: 0.4 },
    { chord: "", duration: 0.4 },
  ],
);

export default P2;