import { Piece } from "../../classes/Piece.jsx";

const P7 = new Piece(
  "7",
  "Silent Night",
  "Silent Night is one of the most peaceful and cherished Christmas carols ever written. Its gentle, lullaby-like melody flows softly from note to note, creating a warm and calming atmosphere that feels magical every time you play it. Perfect for the holiday season — or any time you need a moment of quiet beauty!",
  "silentnight",
  "/Pieces/P7.jpg",
  "Joseph Mohr",
  "2",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/shiningWhite.png",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/shiningMoon.png",
  "/AssetsForPiano/cloud.png",
  [
    { chord: "G4", fingers: "3", duration: 0.75 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "G4", fingers: "3", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 1.5 },
    { chord: "G4", fingers: "3", duration: 0.75 },
    { chord: "A4", fingers: "4", duration: 0.25 },
    { chord: "G4", fingers: "3", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 1.5 },

    { chord: "D5", fingers: "5", duration: 1.0 },
    { chord: "D5", fingers: "5", duration: 0.5 },
    { chord: "B4", fingers: "3", duration: 1.5 },
    { chord: "C5", fingers: "4", duration: 1.0 },
    { chord: "C5", fingers: "4", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 1.5 },

    { chord: "A4", fingers: "3", duration: 1.0 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "5", duration: 0.75 },
    { chord: "B4", fingers: "4", duration: 0.25 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "G4", fingers: "2", duration: 0.75 },
    { chord: "A4", fingers: "3", duration: 0.25 },
    { chord: "G4", fingers: "2", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 1.5 },

    { chord: "D5", fingers: "3", duration: 1.0 },
    { chord: "D5", fingers: "3", duration: 0.5 },
    { chord: "F5", fingers: "5", duration: 0.75 },
    { chord: "D5", fingers: "3", duration: 0.25 },
    { chord: "B4", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "2", duration: 1.5 },
    { chord: "E5", fingers: "4", duration: 1.5 },
  
    { chord: "C5", fingers: "5", duration: 0.5 },
    { chord: "G4", fingers: "2", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "5", duration: 0.5 },
    { chord: "F4", fingers: "4", duration: 0.5 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
  ],
  [
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "B3", fingers: "2", duration: 0.5 },
    { chord: "A3", fingers: "3", duration: 0.5 },
    { chord: "G3", fingers: "4", duration: 1.5 },
    { chord: "G3", fingers: "4", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },

    { chord: "F3", fingers: "5", duration: 1.5 },
    { chord: "F3", fingers: "5", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "B3", fingers: "2", duration: 0.5 },
    { chord: "A3", fingers: "3", duration: 0.5 },

    { chord: "G3", fingers: "4", duration: 1.5 },
    { chord: "G3", fingers: "4", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },

    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "G3", fingers: "4", duration: 1.5 },
    { chord: "", duration: 1.5 },
  ]
);

export default P7;