import { Piece } from "../../classes/Piece.jsx";

const P9 = new Piece(
  "9",
  "Moonlight Sonata",
  "Moonlight Sonata is a masterpiece of piano composition, known for its haunting melody and emotional depth. This piece showcases the piano's ability to convey a wide range of emotions, from gentle serenity to passionate intensity.",
  "moonlightsonata",
  "/Pieces/P9.png",
  "#F5D576",
  "Ludwig van Beethoven",
  "3",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/shiningMoon.png",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/cloud.png",
  "/AssetsForPiano/shiningWhite.png",
  "/AssetsForPiano/cloud.png",
  [
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },

    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },

    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "A4", fingers: "3", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "A4", fingers: "3", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 0.4 },

    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "3", duration: 0.4 },
    { chord: "A#4", fingers: "4", duration: 0.4 },
    { chord: "C#4", fingers: "1", duration: 0.4 },
    { chord: "G4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "4", duration: 0.4 },

    { chord: "B3", fingers: "1", duration: 0.4 },
    { chord: "D#4", fingers: "2", duration: 0.4 },
    { chord: "G#4", fingers: "5", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#5", fingers: "5", duration: 1.0 },
    { chord: "D#5", fingers: "5", duration: 0.2 },

    { chord: "D#5", fingers: "5", duration: 3.6, movingTime: 0.4 },
    { chord: "A#4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "A#4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "A#4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "4", duration: 0.4 },
    { chord: "D#5", fingers: "5", duration: 1.0 },
    { chord: "D#5", fingers: "5", duration: 0.2 },
    { chord: "D#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "3", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "4", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "4", duration: 0.4 },
    { chord: "D#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "F#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "F#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "A#4", fingers: "2", duration: 0.4 },
    { chord: "F#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "A#4", fingers: "2", duration: 0.4 },

    { chord: "B4", fingers: "3", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "B4", fingers: "3", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 0.4 },
    { chord: "F#5", fingers: "5", duration: 1.0 },
    { chord: "F#5", fingers: "5", duration: 0.2 },

    { chord: "F#5", fingers: "5", duration: 3.6, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "F#5", fingers: "5", duration: 1.0 },
    { chord: "F#5", fingers: "5", duration: 0.2 },

    { chord: "F#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 0.4 },
    { chord: "G5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "C#5", fingers: "1", duration: 0.4 },
    { chord: "D#5", fingers: "2", duration: 0.4 },
    { chord: "G#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "B4", fingers: "1", duration: 0.4 },
    { chord: "D#5", fingers: "2", duration: 0.4 },
    { chord: "A#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "A#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "B5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "D#5", fingers: "2", duration: 0.4 },
    { chord: "G#5", fingers: "4", duration: 0.4 },
    { chord: "B4", fingers: "1", duration: 0.4 },
    { chord: "D#5", fingers: "2", duration: 0.4 },
    { chord: "G#5", fingers: "4", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "A4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "G5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },

    { chord: "G#5", fingers: "5", duration: 3.6, movingTime: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "G5", fingers: "1", duration: 1.2, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },

    { chord: "G#5", fingers: "5", duration: 3.6, movingTime: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "G5", fingers: "1", duration: 1.2, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },

    { chord: "G#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C5", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "3", duration: 0.4 },
    { chord: "G#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },

    { chord: "F#5", fingers: "5", duration: 3.6, movingTime: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "F#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "2", duration: 0.4 },
    { chord: "E5", fingers: "4", duration: 0.4 },
    { chord: "F#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 0.4 },

    { chord: "E5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 0.4 },
    { chord: "E5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "A#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "3", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 1.2, movingTime: 0.4 },
    { chord: "A#4", fingers: "1", duration: 0.4 },
    { chord: "C#5", fingers: "3", duration: 0.4 },
    { chord: "D#5", fingers: "4", duration: 1.2, movingTime: 0.4 },
    { chord: "G#4", fingers: "1", duration: 0.4 },
    { chord: "B4", fingers: "2", duration: 0.4 },

    { chord: "C#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "3", duration: 0.4 },
    { chord: "C#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "3", duration: 0.4 },

    { chord: "D#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "3", duration: 0.4 },

    { chord: "D#5", fingers: "5", duration: 2.4, movingTime: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "3", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "3", duration: 0.4 },

    { chord: "D#5", fingers: "5", duration: 1.2, movingTime: 0.4 },
    { chord: "G4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "3", duration: 0.4 },
    { chord: "C#4", fingers: "1", duration: 0.4 },
    { chord: "G4", fingers: "2", duration: 0.4 },
    { chord: "A#4", fingers: "4", duration: 0.4 },

    { chord: "G#4", fingers: "3", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "3", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },

    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },

    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "A4", fingers: "3", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 0.4 },
    { chord: "E4", fingers: "1", duration: 0.4 },
    { chord: "A4", fingers: "3", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 0.4 },

    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G4", fingers: "2", duration: 0.4 },
    { chord: "C#5", fingers: "5", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "2", duration: 0.4 },
    { chord: "B4", fingers: "4", duration: 0.4 },
    { chord: "D#4", fingers: "1", duration: 0.4 },
    { chord: "G#4", fingers: "3", duration: 0.4 },
    { chord: "A#4", fingers: "4", duration: 0.4 },
    { chord: "C#4", fingers: "1", duration: 0.4 },
    { chord: "G4", fingers: "3", duration: 0.4 },
    { chord: "A#4", fingers: "5", duration: 0.4 },

    { chord: "B3 G#4", fingers: "1 4", duration: 2.4 },
    { chord: "B3 G#4", fingers: "1 4", duration: 2.4 },
    { chord: "B3 G#4", fingers: "1 4", duration: 4.8 },
  ],

  [
    { chord: "G#3", fingers: "1", duration: 4.8 },
    { chord: "F#3", fingers: "2", duration: 4.8 },
    { chord: "E3", fingers: "3", duration: 2.4 },
    { chord: "C#3", fingers: "5", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 2.4 },
    { chord: "G#3", fingers: "1", duration: 4.8 },
    { chord: "G3", fingers: "2", duration: 4.8 },
    { chord: "G#3", fingers: "1", duration: 2.4 },
    { chord: "C#3", fingers: "5", duration: 2.4 },
    { chord: "F#3", fingers: "2", duration: 2.4 },
    { chord: "F#3", fingers: "2", duration: 2.4 },

    { chord: "B3", fingers: "1", duration: 4.8 },
    { chord: "A#3", fingers: "2", duration: 4.8 },
    { chord: "B3", fingers: "1", duration: 2.4 },
    { chord: "A#3", fingers: "2", duration: 1.2 },
    { chord: "G#3", fingers: "3", duration: 1.2 },
    { chord: "G3", fingers: "4", duration: 2.4 },
    { chord: "G#3", fingers: "1", duration: 2.4 },
    { chord: "C#3", fingers: "5", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 2.4 },

    { chord: "G#3", fingers: "1", duration: 6.0 },
    { chord: "C#4", fingers: "2", duration: 1.2 },
    { chord: "E4", fingers: "1", duration: 1.2 },
    { chord: "C#4", fingers: "2", duration: 1.2 },

    { chord: "G#3", fingers: "5", duration: 6.0 },
    { chord: "C#4", fingers: "2", duration: 1.2 },
    { chord: "E4", fingers: "1", duration: 1.2 },
    { chord: "C#4", fingers: "2", duration: 1.2 },

    { chord: "G#3", fingers: "5", duration: 2.4 },
    { chord: "C#4", fingers: "1", duration: 2.4 },
    { chord: "A#3", fingers: "2", duration: 3.6 },
    { chord: "B3", fingers: "1", duration: 1.2 },
    { chord: "G#3", fingers: "3", duration: 1.2 },
    { chord: "A#3", fingers: "2", duration: 1.2 },
    { chord: "G3", fingers: "4", duration: 1.2 },
    { chord: "G#3", fingers: "1", duration: 1.2 },
    { chord: "E3", fingers: "3", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 1.2 },
    { chord: "C#3", fingers: "5", duration: 1.2 },
    { chord: "D#3", fingers: "4", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 2.4 },

    { chord: "G#3", fingers: "1", duration: 4.8 },
    { chord: "F#3", fingers: "2", duration: 4.8 },
    { chord: "E3", fingers: "3", duration: 2.4 },
    { chord: "C#3", fingers: "5", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 2.4 },
    { chord: "D#3", fingers: "4", duration: 2.4 },

    { chord: "G#3", fingers: "1", duration: 2.4 },
    { chord: "G#3", fingers: "1", duration: 2.4 },
    { chord: "G#3", fingers: "1", duration: 4.8 },
  ]
);

export default P9;