import { FingerPiece } from "../../classes/FingerPiece.jsx";

const P4 = new FingerPiece(
  "Spring from the Four Seasons",
  "Spring is the opening movement of Vivaldi's Four Seasons — one of the most cheerful and recognizable FingerPieces in all of classical music. The melody dances along with a bright, energetic feel that perfectly captures the freshness of a new season blooming to life. It's a joy to play and even more of a joy to listen to!",
  "p4",
  "/FingerPieces/P4.png",
  [
    { chord: "", duration: 0.4 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "G5", fingers: "5", duration: 1.2 },
    { chord: "G5", fingers: "5", duration: 0.2 },
    { chord: "F5", fingers: "4", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "G5", fingers: "5", duration: 1.2 },
    { chord: "G5", fingers: "5", duration: 0.2 },
    { chord: "F5", fingers: "4", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "F5", fingers: "4", duration: 0.2 },
    { chord: "G5", fingers: "5", duration: 0.2 },
    { chord: "F5", fingers: "4", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 1.2 },

    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "G5", fingers: "5", duration: 1.2 },
    { chord: "G5", fingers: "5", duration: 0.2 },
    { chord: "F5", fingers: "4", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "G5", fingers: "5", duration: 1.2 },
    { chord: "G5", fingers: "5", duration: 0.2 },
    { chord: "F5", fingers: "4", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "F5", fingers: "4", duration: 0.2 },
    { chord: "G5", fingers: "5", duration: 0.2 },
    { chord: "F5", fingers: "4", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 1.2 },

    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "F5", fingers: "3", duration: 0.2 },
    { chord: "E5", fingers: "2", duration: 0.2 },
    { chord: "F5", fingers: "3", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.8 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "F5", fingers: "3", duration: 0.2 },
    { chord: "E5", fingers: "2", duration: 0.2 },
    { chord: "F5", fingers: "3", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.8 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.8 },
    { chord: "F5", fingers: "4", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.4 },
    { chord: "C5", fingers: "1", duration: 1.2 },

    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "F5", fingers: "3", duration: 0.2 },
    { chord: "E5", fingers: "2", duration: 0.2 },
    { chord: "F5", fingers: "3", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.8 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "F5", fingers: "3", duration: 0.2 },
    { chord: "E5", fingers: "2", duration: 0.2 },
    { chord: "F5", fingers: "3", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.8 },
    { chord: "C5", fingers: "1", duration: 0.4 },
    { chord: "A5", fingers: "5", duration: 0.4 },
    { chord: "G5", fingers: "4", duration: 0.8 },
    { chord: "F5", fingers: "4", duration: 0.4 },
    { chord: "E5", fingers: "3", duration: 0.4 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "C5", fingers: "1", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.2 },
    { chord: "E5", fingers: "3", duration: 0.2 },
    { chord: "D5", fingers: "2", duration: 0.4 },
    { chord: "C5", fingers: "1", duration: 1.6 },
  ],
  [
    { chord: "", duration: 0.8 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 0.8 },
    { chord: "F4", fingers: "3", duration: 0.4 },
    { chord: "F#4", fingers: "2", duration: 0.4 },
    { chord: "G4", fingers: "1", duration: 1.6 },

    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "C4", fingers: "5", duration: 0.8 },
    { chord: "F4", fingers: "3", duration: 0.4 },
    { chord: "F#4", fingers: "2", duration: 0.4 },
    { chord: "G4", fingers: "1", duration: 1.6 },

    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "F4", fingers: "2", duration: 0.4 },
    { chord: "E4", fingers: "3", duration: 0.4 },
    { chord: "", duration: 0.8 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "F4", fingers: "2", duration: 0.4 },
    { chord: "E4", fingers: "3", duration: 0.4 },
    { chord: "", duration: 0.8 },
    { chord: "F4", fingers: "2", duration: 0.4 },
    { chord: "E4", fingers: "3", duration: 0.4 },
    { chord: "", duration: 0.4 },
    { chord: "D4", fingers: "4", duration: 0.4 },
    { chord: "C4", fingers: "5", duration: 0.8 },
    { chord: "G4", fingers: "1", duration: 0.8 },
    { chord: "C4 E4 G4", fingers: "5 3 1", duration: 1.6 },
    
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "F4", fingers: "2", duration: 0.4 },
    { chord: "E4", fingers: "3", duration: 0.4 },
    { chord: "", duration: 0.8 },
    { chord: "C4", fingers: "5", duration: 1.6 },
    { chord: "F4", fingers: "2", duration: 0.4 },
    { chord: "E4", fingers: "3", duration: 0.4 },
    { chord: "", duration: 0.8 },
    { chord: "F4", fingers: "2", duration: 0.4 },
    { chord: "E4", fingers: "3", duration: 0.4 },
    { chord: "", duration: 0.4 },
    { chord: "D4", fingers: "4", duration: 0.4 },
    { chord: "C4", fingers: "5", duration: 0.8 },
    { chord: "G4", fingers: "1", duration: 0.8 },
    { chord: "C4 E4 G4", fingers: "5 3 1", duration: 1.6 },
  ]
);

export default P4;