import { FingerPiece } from "../../classes/FingerPiece.jsx";

const P5 = new FingerPiece(
  "Greensleeves",
  "Greensleeves is a timeless English folk melody that has been beloved for centuries. Its gentle, flowing rhythm gives it a wistful and romantic feel that's unlike anything else you'll play. The left hand keeps a steady, song-like accompaniment while the right hand sings out the iconic tune — hauntingly beautiful from the very first note!",
  "p5",
  "/FingerPieces/P5.png",
  [
    { chord: "", duration: 1.0 },
    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "2", duration: 1.0 },
    { chord: "D5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "4", duration: 0.75 },
    { chord: "F5", fingers: "5", duration: 0.25 },
    { chord: "E5", fingers: "4", duration: 0.5 },
    { chord: "D5", fingers: "3", duration: 1.0 },
    { chord: "B4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.75 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 1.0 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "3", duration: 0.75 },
    { chord: "G#4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "B4", fingers: "4", duration: 1.0 },
    { chord: "G#4", fingers: "2", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 1.0 },

    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "2", duration: 1.0 },
    { chord: "D5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "4", duration: 0.75 },
    { chord: "F5", fingers: "5", duration: 0.25 },
    { chord: "E5", fingers: "4", duration: 0.5 },
    { chord: "D5", fingers: "3", duration: 1.0 },
    { chord: "B4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.75 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.75 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "G#4", fingers: "3", duration: 0.75 },
    { chord: "F#4", fingers: "2", duration: 0.25 },
    { chord: "G#4", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "4", duration: 1.5 },
    { chord: "A4", fingers: "4", duration: 1.5 },
  
    { chord: "G5", fingers: "5", duration: 1.5 },
    { chord: "G5", fingers: "5", duration: 0.75 },
    { chord: "F#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 1.0 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.75 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 1.0 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "3", duration: 0.75 },
    { chord: "G#4", fingers: "2", duration: 0.25 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "B4", fingers: "4", duration: 1.0 },
    { chord: "G#4", fingers: "2", duration: 0.5 },
    { chord: "E4", fingers: "1", duration: 1.5 },

    { chord: "G5", fingers: "5", duration: 1.5 },
    { chord: "G5", fingers: "5", duration: 0.75 },
    { chord: "F#5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 1.0 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "G4", fingers: "1", duration: 0.75 },
    { chord: "A4", fingers: "2", duration: 0.25 },
    { chord: "B4", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "4", duration: 0.75 },
    { chord: "B4", fingers: "3", duration: 0.25 },
    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "G#4", fingers: "3", duration: 0.75 },
    { chord: "F#4", fingers: "2", duration: 0.25 },
    { chord: "G#4", fingers: "3", duration: 0.5 },
    { chord: "A4", fingers: "4", duration: 1.5 },
    { chord: "A4", fingers: "4", duration: 1.5 },
  ],
  [
    { chord: "", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "F3", fingers: "4", duration: 1.5 },
    { chord: "F3", fingers: "4", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },

    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "F3", fingers: "4", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },

    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "F3", fingers: "4", duration: 1.5 },
    { chord: "F3", fingers: "4", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },

    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "C4", fingers: "1", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "G3", fingers: "3", duration: 1.5 },
    { chord: "F3", fingers: "4", duration: 1.5 },
    { chord: "E3", fingers: "5", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
    { chord: "A3", fingers: "2", duration: 1.5 },
  ]
);

export default P5;