import { FingerPiece } from "../../classes/FingerPiece.jsx";

const P6 = new FingerPiece(
  "Happy Birthday to You",
  "Happy Birthday to You is the most sung song in the world — and now you can play it on the piano! Its cheerful waltz rhythm makes it instantly feel festive and fun. Whether you're surprising someone at their party or just playing for the joy of it, this one is always a crowd-pleaser!",
  "p6",
  "/FingerPieces/P6.png",
  [
    { chord: "", duration: 1.0 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "F4", fingers: "4", duration: 0.5 },
    { chord: "E4", fingers: "3", duration: 1.0 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "5", duration: 0.5 },
    { chord: "F4", fingers: "4", duration: 1.0 },

    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.5 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "F4", fingers: "1", duration: 0.5 },
    { chord: "E4", fingers: "3", duration: 0.5 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "D4", fingers: "2", duration: 0.25 },
    { chord: "E4", fingers: "3", duration: 0.25 },
    { chord: "F4", fingers: "4", duration: 0.5 },
    { chord: "F4", fingers: "4", duration: 0.5 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "G4", fingers: "5", duration: 1.0 },

    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "F4", fingers: "4", duration: 0.5 },
    { chord: "E4", fingers: "3", duration: 1.0 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "C4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "5", duration: 0.5 },
    { chord: "F4", fingers: "4", duration: 1.0 },
    
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C4", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "5", duration: 0.5 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "F4", fingers: "1", duration: 0.5 },
    { chord: "E4", fingers: "3", duration: 0.5 },
    { chord: "D4", fingers: "2", duration: 0.5 },
    { chord: "A#4", fingers: "4", duration: 0.25 },
    { chord: "A#4", fingers: "4", duration: 0.25 },
    { chord: "A4", fingers: "3", duration: 0.5 },
    { chord: "F4", fingers: "1", duration: 0.5 },
    { chord: "G4", fingers: "2", duration: 0.5 },
    { chord: "F4", fingers: "1", duration: 1.5 },
  ],
  [
    { chord: "", duration: 1.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
    { chord: "C3 A#3", fingers: "5 1", duration: 1.5 },
    { chord: "C3 A#3", fingers: "5 1", duration: 1.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
    { chord: "F3 A#3", fingers: "4 1", duration: 1.5 },
    { chord: "G3 B3", fingers: "3 1", duration: 1.5 },
    { chord: "C3 A#3", fingers: "5 1", duration: 1.5 },

    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
    { chord: "C3 A#3", fingers: "5 1", duration: 1.5 },
    { chord: "C3 A#3", fingers: "5 1", duration: 1.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
    { chord: "F3 A#3", fingers: "4 1", duration: 1.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.0 },
    { chord: "C3 A#3", fingers: "5 1", duration: 0.5 },
    { chord: "F3 A3", fingers: "4 2", duration: 1.5 },
  ]
);

export default P6;