import { Piece } from "../Piece.jsx";

const P2 = new Piece(
  "The Entertainer",
  "Description not available",
  "p2",
  "/PianoPieces/P2.jpg",
  [
    { note: "R", duration: 0.5 },
    { note: "D4", duration: 0.25 },
    { note: "D#4", duration: 0.25 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 0.5 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 0.5 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 5.75 },
    { note: "D4", duration: 0.25 },
    { note: "D#4", duration: 0.25 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 0.5 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 0.5 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 1.75 },
    { note: "A4", duration: 0.25 },
    { note: "G4", duration: 0.25 },
    { note: "F#4", duration: 0.25 },
    { note: "A4", duration: 0.25 },
    { note: "R", duration: 3.0 },
    { note: "D4", duration: 0.25 },
    { note: "D#4", duration: 0.25 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 0.5 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 0.5 },
    { note: "E4", duration: 0.25 },
    { note: "R", duration: 6.25 },
    { note: "C4", duration: 1.0 },
    { note: "A#3", duration: 1.0 },
    { note: "A3", duration: 1.0 },
    { note: "G#3", duration: 1.0 },
    { note: "G3", duration: 2.0 },
    { note: "C4", duration: 0.5 },
    { note: "G3", duration: 0.5 },
    { note: "C3", duration: 0.5 },
    { note: "R", duration: 0.5 },
  ],
  [
    { note: "R", duration: 1.25 },
    { note: "C5", duration: 0.5 },
    { note: "R", duration: 0.25 },
    { note: "C5", duration: 0.5 },
    { note: "R", duration: 0.25 },
    { note: "C5", duration: 1.5 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "D#5", duration: 0.25 },
    { note: "E5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "E5", duration: 0.5 },
    { note: "B4", duration: 0.25 },
    { note: "D5", duration: 0.5 },
    { note: "C5", duration: 1.5 },
    { note: "R", duration: 0.75 },
    { note: "C5", duration: 0.5 },
    { note: "R", duration: 0.25 },
    { note: "C5", duration: 0.5 },
    { note: "R", duration: 0.25 },
    { note: "C5", duration: 1.75 },
    { note: "R", duration: 1.0 },
    { note: "C5", duration: 0.25 },
    { note: "E5", duration: 0.5 },
    { note: "D5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "A4", duration: 0.25 },
    { note: "D5", duration: 1.5 },
    { note: "R", duration: 0.75 },
    { note: "C5", duration: 0.5 },
    { note: "R", duration: 0.25 },
    { note: "C5", duration: 0.5 },
    { note: "R", duration: 0.25 },
    { note: "C5", duration: 1.5 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "D#5", duration: 0.25 },
    { note: "E5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "E5", duration: 0.5 },
    { note: "B4", duration: 0.25 },
    { note: "D5", duration: 0.5 },
    { note: "C5", duration: 1.5 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "E5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "E5", duration: 0.5 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "E5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "E5", duration: 0.5 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "E5", duration: 0.25 },
    { note: "C5", duration: 0.25 },
    { note: "D5", duration: 0.25 },
    { note: "E5", duration: 0.5 },
    { note: "B4", duration: 0.25 },
    { note: "D5", duration: 0.5 },
    { note: "C5", duration: 1.5 },
    { note: "R", duration: 0.5 },
  ]
);

export default P2;