import { Piece } from "../../classes/Piece.jsx";

const P3 = new Piece(
  "3",
  "Ode To Joy",
  "Ode to Joy is one of the most beloved melodies in all of classical music, taken from Beethoven's legendary Ninth Symphony. This uplifting piece has a steady, marching rhythm that feels both powerful and joyful — perfect for lifting your spirits while you play. Once you know it, you'll never forget it!",
  "odetojoy",
  "/PianoPieces/P3.png",
  "Ludwig van Beethoven",
  "2",
  "/AssetsForPiano/cartoonCloud.png",
  "/AssetsForPiano/sun.png",
  "/AssetsForPiano/cartoonCloud.png",
  "/AssetsForPiano/cartoonCloud.png",
  "/AssetsForPiano/flyingBird.png",
  "/AssetsForPiano/cartoonCloud.png",
  [
    { chord: "E5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "F5", duration: 0.5 },
    { chord: "G5", duration: 0.5 },
    { chord: "G5", duration: 0.5 },
    { chord: "F5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "E5", duration: 0.75 },
    { chord: "D5", duration: 0.25 },
    { chord: "D5", duration: 1.0 },

    { chord: "E5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "F5", duration: 0.5 },
    { chord: "G5", duration: 0.5 },
    { chord: "G5", duration: 0.5 },
    { chord: "F5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 0.75 },
    { chord: "C5", duration: 0.25 },
    { chord: "C5", duration: 1.0 },

    { chord: "D5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.25 },
    { chord: "F5", duration: 0.25 },
    { chord: "E5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.25 },
    { chord: "F5", duration: 0.25 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "G4", duration: 0.5 },

    { chord: "E5", duration: 1.0 },
    { chord: "E5", duration: 0.5 },
    { chord: "F5", duration: 0.5 },
    { chord: "G5", duration: 0.5 },
    { chord: "G5", duration: 0.5 },
    { chord: "F5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "C5", duration: 0.5 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 0.75 },
    { chord: "C5", duration: 0.25 },
    { chord: "C5", duration: 1.0 },
  ],
  [
    { chord: "C4", duration: 2.0 },
    { chord: "G4", duration: 2.0 },
    { chord: "C4", duration: 2.0 },
    { chord: "G4", duration: 2.0 },

    { chord: "C4", duration: 2.0 },
    { chord: "G4", duration: 2.0 },
    { chord: "C4", duration: 2.0 },
    { chord: "F4 G4", duration: 1.0 },
    { chord: "E4 G4", duration: 1.0 },

    { chord: "G4", duration: 2.0 },
    { chord: "G4", duration: 2.0 },
    { chord: "G4", duration: 1.0 },
    { chord: "G#4", duration: 1.0 },
    { chord: "A4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "G4", duration: 1.0 },

    { chord: "C4", duration: 2.0 },
    { chord: "G4", duration: 2.0 },
    { chord: "C4", duration: 2.0 },
    { chord: "F4 G4", duration: 1.0 },
    { chord: "C4 E4 G4", duration: 1.0 },
  ]
);

export default P3;