import { Piece } from "../../classes/Piece.jsx";

const P3 = new Piece(
  "Ode To Joy",
  "Ode to Joy is one of the most beloved melodies in all of classical music, taken from Beethoven's legendary Ninth Symphony. This uplifting piece has a steady, marching rhythm that feels both powerful and joyful — perfect for lifting your spirits while you play. Once you know it, you'll never forget it!",
  "p3",
  "/PianoPieces/P3.png",
  [
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.75 },
    { chord: "D5", fingers: "2", duration: 0.25 },
    { chord: "D5", fingers: "2", duration: 1.0 },

    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.75 },
    { chord: "C5", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "1", duration: 1.0 },

    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "F5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.25 },
    { chord: "F5", fingers: "4", duration: 0.25 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "3", duration: 0.5 },
    { chord: "", duration: 0.5 },

    { chord: "E5", fingers: "3", duration: 1.0 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "G5", fingers: "5", duration: 0.5 },
    { chord: "F5", fingers: "4", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "C5", fingers: "1", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.5 },
    { chord: "E5", fingers: "3", duration: 0.5 },
    { chord: "D5", fingers: "2", duration: 0.75 },
    { chord: "C5", fingers: "1", duration: 0.25 },
    { chord: "C5", fingers: "1", duration: 1.0 },
  ],
  [
    { chord: "C4", fingers: "5", duration: 2.0 },
    { chord: "G4", fingers: "1", duration: 2.0 },
    { chord: "C4", fingers: "5", duration: 2.0 },
    { chord: "G4", fingers: "1", duration: 2.0 },

    { chord: "C4", fingers: "5", duration: 2.0 },
    { chord: "G4", fingers: "1", duration: 2.0 },
    { chord: "C4", fingers: "5", duration: 2.0 },
    { chord: "F4 G4", fingers: "2 1", duration: 1.0 },
    { chord: "E4 G4", fingers: "3 1", duration: 1.0 },

    { chord: "G4", fingers: "3", duration: 2.0 },
    { chord: "G4", fingers: "3", duration: 2.0 },
    { chord: "G4", fingers: "3", duration: 1.0 },
    { chord: "G#4", fingers: "2", duration: 1.0 },
    { chord: "A4", fingers: "1", duration: 0.5 },
    { chord: "F4", fingers: "3", duration: 0.5 },
    { chord: "G4", fingers: "2", duration: 1.0 },

    { chord: "C4", fingers: "5", duration: 2.0 },
    { chord: "G4", fingers: "1", duration: 2.0 },
    { chord: "C4", fingers: "5", duration: 2.0 },
    { chord: "F4 G4", fingers: "2 1", duration: 1.0 },
    { chord: "C4 E4 G4", fingers: "5 3 1", duration: 1.0 },
  ]
);

export default P3;