import { Piece } from "../../classes/Piece.jsx";

const P4 = new Piece(
  "4",
  "Spring from the Four Seasons",
  "Spring is the opening movement of Vivaldi's Four Seasons — one of the most cheerful and recognizable pieces in all of classical music. The melody dances along with a bright, energetic feel that perfectly captures the freshness of a new season blooming to life. It's a joy to play and even more of a joy to listen to!",
  "springfromthefourseasons",
  "/PianoPieces/P4.png",
  "Antonio Vivaldi",
  "2",
  "/AssetsForPiano/none.png",
  "/AssetsForPiano/cherryBlossom.png",
  "/AssetsForPiano/cherryBlossom.png",
  "/AssetsForPiano/cartoonCloud.png",
  "/AssetsForPiano/flyingBird.png",
  "/AssetsForPiano/cartoonCloud.png",
  [
    { chord: "R", duration: 0.4 },
    { chord: "C5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 0.2 },
    { chord: "C5", duration: 0.2 },
    { chord: "G5", duration: 1.2 },
    { chord: "G5", duration: 0.2 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 0.2 },
    { chord: "C5", duration: 0.2 },
    { chord: "G5", duration: 1.2 },
    { chord: "G5", duration: 0.2 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.4 },
    { chord: "F5", duration: 0.2 },
    { chord: "G5", duration: 0.2 },
    { chord: "F5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 1.2 },

    { chord: "C5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 0.2 },
    { chord: "C5", duration: 0.2 },
    { chord: "G5", duration: 1.2 },
    { chord: "G5", duration: 0.2 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 0.2 },
    { chord: "C5", duration: 0.2 },
    { chord: "G5", duration: 1.2 },
    { chord: "G5", duration: 0.2 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.4 },
    { chord: "F5", duration: 0.2 },
    { chord: "G5", duration: 0.2 },
    { chord: "F5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 1.2 },

    { chord: "C5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.2 },
    { chord: "F5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "A5", duration: 0.4 },
    { chord: "G5", duration: 0.8 },
    { chord: "C5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.2 },
    { chord: "F5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "A5", duration: 0.4 },
    { chord: "G5", duration: 0.8 },
    { chord: "C5", duration: 0.4 },
    { chord: "A5", duration: 0.4 },
    { chord: "G5", duration: 0.8 },
    { chord: "F5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 0.2 },
    { chord: "C5", duration: 0.2 },
    { chord: "D5", duration: 0.2 },
    { chord: "E5", duration: 0.2 },
    { chord: "D5", duration: 0.4 },
    { chord: "C5", duration: 1.2 },

    { chord: "C5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.2 },
    { chord: "F5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "A5", duration: 0.4 },
    { chord: "G5", duration: 0.8 },
    { chord: "C5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "F5", duration: 0.2 },
    { chord: "E5", duration: 0.2 },
    { chord: "F5", duration: 0.4 },
    { chord: "G5", duration: 0.4 },
    { chord: "A5", duration: 0.4 },
    { chord: "G5", duration: 0.8 },
    { chord: "C5", duration: 0.4 },
    { chord: "A5", duration: 0.4 },
    { chord: "G5", duration: 0.8 },
    { chord: "F5", duration: 0.4 },
    { chord: "E5", duration: 0.4 },
    { chord: "D5", duration: 0.2 },
    { chord: "C5", duration: 0.2 },
    { chord: "D5", duration: 0.2 },
    { chord: "E5", duration: 0.2 },
    { chord: "D5", duration: 0.4 },
    { chord: "C5", duration: 1.6 },
  ],
  [
    { chord: "R", duration: 0.8 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 0.8 },
    { chord: "F4", duration: 0.4 },
    { chord: "F#4", duration: 0.4 },
    { chord: "G4", duration: 1.6 },

    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 1.6 },
    { chord: "C4", duration: 0.8 },
    { chord: "F4", duration: 0.4 },
    { chord: "F#4", duration: 0.4 },
    { chord: "G4", duration: 1.6 },

    { chord: "C4", duration: 1.6 },
    { chord: "F4", duration: 0.4 },
    { chord: "E4", duration: 0.4 },
    { chord: "R", duration: 0.8 },
    { chord: "C4", duration: 1.6 },
    { chord: "F4", duration: 0.4 },
    { chord: "E4", duration: 0.4 },
    { chord: "R", duration: 0.8 },
    { chord: "F4", duration: 0.4 },
    { chord: "E4", duration: 0.4 },
    { chord: "R", duration: 0.4 },
    { chord: "D4", duration: 0.4 },
    { chord: "C4", duration: 0.8 },
    { chord: "G4", duration: 0.8 },
    { chord: "C4 E4 G4", duration: 1.6 },
    
    { chord: "C4", duration: 1.6 },
    { chord: "F4", duration: 0.4 },
    { chord: "E4", duration: 0.4 },
    { chord: "R", duration: 0.8 },
    { chord: "C4", duration: 1.6 },
    { chord: "F4", duration: 0.4 },
    { chord: "E4", duration: 0.4 },
    { chord: "R", duration: 0.8 },
    { chord: "F4", duration: 0.4 },
    { chord: "E4", duration: 0.4 },
    { chord: "R", duration: 0.4 },
    { chord: "D4", duration: 0.4 },
    { chord: "C4", duration: 0.8 },
    { chord: "G4", duration: 0.8 },
    { chord: "C4 E4 G4", duration: 1.6 },
  ]
);

export default P4;