import { Piece } from "../../classes/Piece.jsx";

const P5 = new Piece(
  "Greensleeves",
  "Greensleeves is a timeless English folk melody that has been beloved for centuries. Its gentle, flowing rhythm gives it a wistful and romantic feel that's unlike anything else you'll play. The left hand keeps a steady, song-like accompaniment while the right hand sings out the iconic tune — hauntingly beautiful from the very first note!",
  "p5",
  "/PianoPieces/P5.png",
  [
    { chord: "R", duration: 1.0 },
    { chord: "A4", duration: 0.5 },
    { chord: "C5", duration: 1.0 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.75 },
    { chord: "F5", duration: 0.25 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 1.0 },
    { chord: "B4", duration: 0.5 },
    { chord: "G4", duration: 0.75 },
    { chord: "A4", duration: 0.25 },
    { chord: "B4", duration: 0.5 },
    { chord: "C5", duration: 1.0 },
    { chord: "A4", duration: 0.5 },
    { chord: "A4", duration: 0.75 },
    { chord: "G#4", duration: 0.25 },
    { chord: "A4", duration: 0.5 },
    { chord: "B4", duration: 1.0 },
    { chord: "G#4", duration: 0.5 },
    { chord: "E4", duration: 1.0 },

    { chord: "A4", duration: 0.5 },
    { chord: "C5", duration: 1.0 },
    { chord: "D5", duration: 0.5 },
    { chord: "E5", duration: 0.75 },
    { chord: "F5", duration: 0.25 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 1.0 },
    { chord: "B4", duration: 0.5 },
    { chord: "G4", duration: 0.75 },
    { chord: "A4", duration: 0.25 },
    { chord: "B4", duration: 0.5 },
    { chord: "C5", duration: 0.75 },
    { chord: "B4", duration: 0.25 },
    { chord: "A4", duration: 0.5 },
    { chord: "G#4", duration: 0.75 },
    { chord: "F#4", duration: 0.25 },
    { chord: "G#4", duration: 0.5 },
    { chord: "A4", duration: 1.5 },
    { chord: "A4", duration: 1.5 },
  
    { chord: "G5", duration: 1.5 },
    { chord: "G5", duration: 0.75 },
    { chord: "F#5", duration: 0.25 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 1.0 },
    { chord: "B4", duration: 0.5 },
    { chord: "G4", duration: 0.75 },
    { chord: "A4", duration: 0.25 },
    { chord: "B4", duration: 0.5 },
    { chord: "C5", duration: 1.0 },
    { chord: "A4", duration: 0.5 },
    { chord: "A4", duration: 0.75 },
    { chord: "G#4", duration: 0.25 },
    { chord: "A4", duration: 0.5 },
    { chord: "B4", duration: 1.0 },
    { chord: "G#4", duration: 0.5 },
    { chord: "E4", duration: 1.5 },

    { chord: "G5", duration: 1.5 },
    { chord: "G5", duration: 0.75 },
    { chord: "F#5", duration: 0.25 },
    { chord: "E5", duration: 0.5 },
    { chord: "D5", duration: 1.0 },
    { chord: "B4", duration: 0.5 },
    { chord: "G4", duration: 0.75 },
    { chord: "A4", duration: 0.25 },
    { chord: "B4", duration: 0.5 },
    { chord: "C5", duration: 0.75 },
    { chord: "B4", duration: 0.25 },
    { chord: "A4", duration: 0.5 },
    { chord: "G#4", duration: 0.75 },
    { chord: "F#4", duration: 0.25 },
    { chord: "G#4", duration: 0.5 },
    { chord: "A4", duration: 1.5 },
    { chord: "A4", duration: 1.5 },
  ],
  [
    { chord: "R", duration: 1.5 },
    { chord: "A3", duration: 1.5 },
    { chord: "A3", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "F3", duration: 1.5 },
    { chord: "F3", duration: 1.5 },
    { chord: "E3", duration: 1.5 },
    { chord: "E3", duration: 1.5 },

    { chord: "A3", duration: 1.5 },
    { chord: "A3", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "F3", duration: 1.5 },
    { chord: "E3", duration: 1.5 },
    { chord: "A3", duration: 1.5 },
    { chord: "A3", duration: 1.5 },

    { chord: "C4", duration: 1.5 },
    { chord: "C4", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "F3", duration: 1.5 },
    { chord: "F3", duration: 1.5 },
    { chord: "E3", duration: 1.5 },
    { chord: "E3", duration: 1.5 },

    { chord: "C4", duration: 1.5 },
    { chord: "C4", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "G3", duration: 1.5 },
    { chord: "F3", duration: 1.5 },
    { chord: "E3", duration: 1.5 },
    { chord: "A3", duration: 1.5 },
    { chord: "A3", duration: 1.5 },
  ]
);

export default P5;