import { Piece } from "../../classes/Piece.jsx";

const P6 = new Piece(
  "6",
  "Happy Birthday to You",
  "Happy Birthday to You is the most sung song in the world — and now you can play it on the piano! Its cheerful waltz rhythm makes it instantly feel festive and fun. Whether you're surprising someone at their party or just playing for the joy of it, this one is always a crowd-pleaser!",
  "happybirthdaytoyou",
  "/PianoPieces/P6.png",
  "The Hill sisters",
  "2",
  "/AssetsForPiano/flyingGift.png",
  "/AssetsForPiano/flyingGift.png",
  "/AssetsForPiano/birthdayCake.png",
  "/AssetsForPiano/flyingGift.png",
  "/AssetsForPiano/happyBirthday.png",
  "/AssetsForPiano/santaGift.png",
  [
    { chord: "R", duration: 1.0 },
    { chord: "C4", duration: 0.25 },
    { chord: "C4", duration: 0.25 },
    { chord: "D4", duration: 0.5 },
    { chord: "C4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "E4", duration: 1.0 },
    { chord: "C4", duration: 0.25 },
    { chord: "C4", duration: 0.25 },
    { chord: "D4", duration: 0.5 },
    { chord: "C4", duration: 0.5 },
    { chord: "G4", duration: 0.5 },
    { chord: "F4", duration: 1.0 },

    { chord: "C4", duration: 0.25 },
    { chord: "C4", duration: 0.25 },
    { chord: "C5", duration: 0.5 },
    { chord: "A4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "E4", duration: 0.5 },
    { chord: "D4", duration: 0.5 },
    { chord: "D4", duration: 0.25 },
    { chord: "E4", duration: 0.25 },
    { chord: "F4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "D4", duration: 0.5 },
    { chord: "G4", duration: 1.0 },

    { chord: "C4", duration: 0.25 },
    { chord: "C4", duration: 0.25 },
    { chord: "D4", duration: 0.5 },
    { chord: "C4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "E4", duration: 1.0 },
    { chord: "C4", duration: 0.25 },
    { chord: "C4", duration: 0.25 },
    { chord: "D4", duration: 0.5 },
    { chord: "C4", duration: 0.5 },
    { chord: "G4", duration: 0.5 },
    { chord: "F4", duration: 1.0 },
    
    { chord: "C4", duration: 0.25 },
    { chord: "C4", duration: 0.25 },
    { chord: "C5", duration: 0.5 },
    { chord: "A4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "E4", duration: 0.5 },
    { chord: "D4", duration: 0.5 },
    { chord: "A#4", duration: 0.25 },
    { chord: "A#4", duration: 0.25 },
    { chord: "A4", duration: 0.5 },
    { chord: "F4", duration: 0.5 },
    { chord: "G4", duration: 0.5 },
    { chord: "F4", duration: 1.5 },
  ],
  [
    { chord: "R", duration: 1.5 },
    { chord: "F3 A3", duration: 1.5 },
    { chord: "C3 A#3", duration: 1.5 },
    { chord: "C3 A#3", duration: 1.5 },
    { chord: "F3 A3", duration: 1.5 },
    { chord: "F3 A3", duration: 1.5 },
    { chord: "F3 A#3", duration: 1.5 },
    { chord: "G3 B3", duration: 1.5 },
    { chord: "C3 A#3", duration: 1.5 },

    { chord: "F3 A3", duration: 1.5 },
    { chord: "C3 A#3", duration: 1.5 },
    { chord: "C3 A#3", duration: 1.5 },
    { chord: "F3 A3", duration: 1.5 },
    { chord: "F3 A3", duration: 1.5 },
    { chord: "F3 A#3", duration: 1.5 },
    { chord: "F3 A3", duration: 1.0 },
    { chord: "C3 A#3", duration: 0.5 },
    { chord: "F3 A3", duration: 1.5 },
  ]
);

export default P6;